### ISSUE TITLE
低版本内核(4.14or4.19等)摘链隐藏进程pid，设备异常死机重启

### ISSUE THREAD

**Issue by Nuthon01** [zfdx123/hack_kernel_pid#2]
设备：Redmi K40
内核版本：4.19.157
insmod proc.ko
ioctl调用hide_process函数，设备异常死机重启。

**Comment by zfdx123** [comment]
是的，问题复现，希望可以取得kp日志

**Comment by Nuthon01** [comment]
手机上如何在内核崩溃前，抓取kernel panic信息log。这方面不太懂呢

**Comment by zfdx123** [comment]
通过启用 ramoops 来实现或许？

**Comment by zfdx123** [comment]
我对代码进行了修改，我现在不能确定是否可以正常在4.19环境下运行，如果你有时间可以测试一下最新提交，有问题最好附带KP日志

**Comment by Nuthon01** [comment]
我的4.19设备已于今年夏天结束了他的寿命，无法再进行测试了。

**Comment by zfdx123** [comment]
好的，非常感谢
